version: '3.8'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - '1883:1883'
    volumes:
      - './broker/config:/mosquitto/config'
      - './broker/data:/mosquitto/data/'
      - './broker/log:/mosquitto/log'
